// Aggregates all ts-rs types into a single `src/types/bindings.ts`.
// ts-rs 9 truncates the output file per type, so the per-type `#[ts(export, export_to = ...)]`
// auto-tests clobber each other when they share a path. This integration test runs after the
// lib unit tests (cargo runs integration test binaries alphabetically; this filename sorts last)
// and rewrites `bindings.ts` with all our types so downstream TS code can import them together.

use std::fs;
use std::path::PathBuf;
use ts_rs::TS;

use skill_sync::config::ownership::{OwnershipClass, OwnershipEntry, OwnershipFile};
use skill_sync::config::settings::Settings;
use skill_sync::config::targets::{Target, TargetKind, TargetsFile};
use skill_sync::discovery::CandidateLocation;
use skill_sync::provenance::{Class, Provenance, Signal};
use skill_sync::types::Health;

fn decl<T: TS + ?Sized + 'static>() -> String {
    format!("export {}\n", T::decl())
}

#[test]
fn aggregate_bindings_ts() {
    let mut out = String::new();
    out.push_str("// This file was generated by ts-rs and an aggregator test. Do not edit manually.\n\n");
    out.push_str(&decl::<Health>());
    out.push_str(&decl::<Settings>());
    out.push_str(&decl::<OwnershipClass>());
    out.push_str(&decl::<OwnershipEntry>());
    out.push_str(&decl::<OwnershipFile>());
    out.push_str(&decl::<TargetKind>());
    out.push_str(&decl::<Target>());
    out.push_str(&decl::<TargetsFile>());
    out.push_str(&decl::<CandidateLocation>());
    out.push_str(&decl::<Class>());
    out.push_str(&decl::<Signal>());
    out.push_str(&decl::<Provenance>());

    let path: PathBuf = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("src")
        .join("types")
        .join("bindings.ts");
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).unwrap();
    }
    fs::write(&path, out).unwrap();
}
