// This file was generated by ts-rs and an aggregator test. Do not edit manually.

export type Health = { ok: boolean, version: string, };
export type Settings = { version: number, source_root: string, package_output_dir: string, show_builtins: boolean, external_bundle_roots: Array<string>, enabled_targets: Array<string>, cowork_package_enabled: boolean, theme: string, mode: string, first_run_completed: boolean, mode_migration_announced: boolean, };
export type OwnershipClass = "mine" | "external" | "ignore";
export type OwnershipEntry = { class: OwnershipClass, source_path: string | null, confirmed_at: string | null, note: string | null, };
export type OwnershipFile = { version: number, skills: { [key: string]: OwnershipEntry }, };
export type TargetKind = "directory-mirror" | "package-only";
export type Target = { install_path: string | null, kind: TargetKind, };
export type TargetsFile = { version: number, targets: { [key: string]: Target }, };
export type CandidateLocation = { dir_name: string, path: string, real_path: string, is_symlink: boolean, };
export type Class = "ToolBuiltin" | "Bundle" | "MineHeuristic" | "Unknown";
export type Signal = "CodexSystemPath" | "CursorBuiltinPath" | "ClaudePluginPath" | "AgentsRoot" | "ExternalBundleRoot" | "SymlinkIntoBundle" | "KnownBundleName" | "FreshUserDir";
export type Provenance = { class: Class, signals: Array<Signal>, };
export type LocationView = { path: string, real_path: string, is_symlink: boolean, hash: string, modified_at: string, provenance: Provenance, };
export type SkillView = { name: string, description: string | null, class: Class, locations: Array<LocationView>, };
export type PlanAction = "Create" | "Update" | "Skip" | "Refuse";
export type PlanRow = { skill: string, target: string, action: PlanAction, source: string, destination: string, reason: string | null, };
export type SyncPlan = { rows: Array<PlanRow>, };
export type DriftStatus = "in-sync" | "drifted-target-newer" | "drifted-source-newer" | "missing-in-target" | "unmanaged" | "refused";
export type AuditEntry = { ts: string, kind: string, data: any, };
export type GitStatus = { branch: string, uncommitted: number, ahead: number, behind: number, has_upstream: boolean, };
