// This file was generated by ts-rs and an aggregator test. Do not edit manually.

export type Health = { ok: boolean, version: string, };
export type Settings = { version: number, source_root: string, package_output_dir: string, show_builtins: boolean, external_bundle_roots: Array<string>, enabled_targets: Array<string>, cowork_package_enabled: boolean, };
export type OwnershipClass = "mine" | "external" | "ignore";
export type OwnershipEntry = { class: OwnershipClass, source_path: string | null, confirmed_at: string | null, note: string | null, };
export type OwnershipFile = { version: number, skills: { [key: string]: OwnershipEntry }, };
export type TargetKind = "directory-mirror" | "package-only";
export type Target = { install_path: string | null, kind: TargetKind, };
export type TargetsFile = { version: number, targets: { [key: string]: Target }, };
